### ISSUE TITLE
Package JSON contains invalid entry for "main" item

### ISSUE THREAD

**Issue by alperyazgan** [DataTables/Dist-Editor-DataTables#1]
Package.json contains the line;

`"main": "js/editor.dataTables.js",`

IMHO this leads the web pack compilation into error when we use the statement `require('datatables.net-editor-dt')();`;
Should it be like the following ?

`"main": "css/editor.dataTables.css",`

Any comments will be appreciated.
Regards,

PS. After installation of the real package `"datatables.net-editor": "^2.0.2"` we use the statement r`equire('datatables.net-editor')();` without any problem, but that package does not contain any css files.

**Comment by AllanJard** [comment]
Thanks for flagging this up - fixed in https://github.com/DataTables/Dist-Editor-DataTables/commit/a2ac65cc98b534d6790528de1ce22ab10d6a1224.
